apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sarr-config
spec:
  accessModes: [ReadWriteOncePod]
  storageClassName: local-path
  resources:
    requests:
      storage: 32Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sarr-data
spec:
  accessModes: [ReadWriteOncePod]
  storageClassName: local-path
  resources:
    requests:
      storage: 32Mi
