---
- name: Caddy HTTP server
  hosts: rpi4
  become: true
  vars:
    caddyfile_path: /etc/caddy/Caddyfile
    caddy_uid: "999"
  tasks:
    - name: Set TS_PERMIT_CERT_UID
      ansible.builtin.lineinfile:
        path: /etc/default/tailscaled
        regexp: "^TS_PERMIT_CERT_UID="
        line: "TS_PERMIT_CERT_UID={{ caddy_uid }}"
      register: lineinfile0
    - name: Restart tailscaled
      ansible.builtin.systemd_service:
        name: tailscaled
        state: restarted
      when: "lineinfile0.changed"
    - name: Copy caddyfile
      ansible.builtin.copy:
        src: ./Caddyfile
        dest: "{{ caddyfile_path }}"
        owner: root
        group: root
        mode: "0644"
    - name: Enable caddy service
      ansible.builtin.systemd_service:
        name: caddy
        enabled: true
        state: restarted

