---
- name: Jellyfin container
  hosts: rpi4
  remote_user: lina
  tasks:
    - name: Jellyfin data volume
      community.docker.docker_volume:
        name: jellyfin-config
    - name: Jellyfin container
      community.docker.docker_container:
        name: jellyfin
        image: jellyfin/jellyfin:10.9.11
        image_name_mismatch: recreate
        restart_policy: unless-stopped
        network_mode: host
        volumes:
          - "jellyfin-config:/config"
        mounts:
          - source: /srv/downloads
            target: /media
            type: bind
        user: "65534:65534"
