---
- name: Jackett search engine
  hosts: rpi4
  vars:
    local_kube: ./kubes/jett.yaml
    remote_kube: ~root/kubes/jett.yaml
  become: true
  tasks:
    - name: Copy jackett kube
      ansible.builtin.copy:
        src: "{{ local_kube }}"
        dest: "{{ remote_kube }}"
    - name: Create prowlarr quadlet
      containers.podman.podman_play:
        state: quadlet
        quadlet_filename: jett-pod
        kube_file: "{{ remote_kube }}"
        network: [services]
        quadlet_options:
          - "PublishPort=127.0.0.1:9117:9117"
          - "[Install]"
          - "WantedBy=multi-user.target"
    - name: Enable quadlet
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: jett-pod.service
        enabled: true
        state: restarted
