- name: k3s
  hosts: rpi4
  become: true
  tasks:
    - name: Write k3s configuration file
      ansible.builtin.copy:
        dest: /etc/rancher/k3s/config.yaml
        content: |
          disable: [traefik]
          disable-cloud-controller: true
    - name: Write k3s environment file
      ansible.builtin.copy:
        dest: /etc/systemd/system/k3s.service.env
        content: |
          GOGC=4
    - name: Restart k3s.service
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: k3s.service
        state: restarted
# disable helm
# gomemlimit
