- name: Initial setup tasks
  hosts: rpi4
  remote_user: lina
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: false
        docker_users:
          - lina
  tasks:
    - name: Set hostname to \"rpi4\"
      hostname:
        name: rpi4
    - name: Create /srv/downloads/
      file:
        path: /srv/downloads/
        state: directory
        mode: '0777'
        owner: 'nobody'
        group: 'nogroup'
