---
- name: PostgreSQL
  hosts: rpi4
  become: true
  vars:
    remote_kube: "~root/kubes/psql.yaml"
    op_psql_uuid: "{{ lookup('ansible.builtin.env', 'op_psql_uuid') }}"
    vault: "{{ lookup('ansible.builtin.env', 'op_vault') }}"
    pgpasswd: "{{ lookup('community.general.onepassword', op_psql_uuid, vault=vault) | b64encode }}"
  tasks:
    - name: Store psql password as secret
      containers.podman.podman_secret:
        name: pgpasswd
        data: "{{ dict(data=dict(pgpasswd=pgpasswd)) | to_json }}"
    - name: Copy pod yaml
      ansible.builtin.copy:
        dest: "{{ remote_kube }}"
        content: |
          ---
          apiVersion: v1
          kind: Pod
          metadata:
            name: psql
          spec:
            volumes: []
            containers:
              - name: psql
                image: docker.io/postgres:17.0-alpine
                containerPorts:
                  - "5432"
                env:
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: pgpasswd
                        name: pgpasswd
    - name: Generate quadlet
      register: quadlet
      containers.podman.podman_play:
        state: quadlet
        quadlet_filename: container-psql
        quadlet_options:
          - "PublishPort=5432:5432"
          - "[Install]"
          - "WantedBy=multi-user.target"
        kube_file: "{{ remote_kube }}"
    - name: Enable quadlet service
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: container-psql
        enabled: true
        state: restarted

