---
- name: qBittorrent
  hosts: rpi4
  vars:
    local_kube: ./kubes/qbt.yaml
    remote_kube: ~root/kubes/qbt.yaml
    kube_name: qbt
  become: true
  tasks:
    - name: Create qbittorrent config directory
      ansible.builtin.file:
        path: "/var/lib/qbittorrent"
        state: directory
        owner: 65534
        group: 65534
        mode: "0755"
    - name: Write Jackett config
      ansible.builtin.copy:
        dest: "/var/lib/qbittorrent/qBittorrent/nova3/engines/jackett.json"
        content: |
          {
            "api_key": "8n8xm6vzn9k578icewr2167t5epuze5b",
            "thread_count": 20,
            "tracker_first": false,
            "url": "http://jett:9117"
          }
        owner: 65534
        group: 65534
    - name: Copy deployment YAML
      ansible.builtin.copy:
        src: "{{ local_kube }}"
        dest: "{{ remote_kube }}"
    - name: Generate deployment quadlet
      containers.podman.podman_play:
        state: quadlet
        quadlet_filename: "{{ kube_name }}-pod"
        kube_file: "{{ remote_kube }}"
        network: [services]
        quadlet_options:
          - "PublishPort=8081:8081"
          - "[Install]"
          - "WantedBy=multi-user.target"
    - name: Enable quadlet
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: "{{ kube_name }}-pod.service"
        enabled: true
        state: restarted
