---
- name: Update services
  hosts: rpi4
  remote_user: lina
  tasks:
    - name: Update qbittorrent
      community.docker.docker_container:
        name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:5.0.0
        pull: true
