apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
spec:
  volumes:
    - name: jellyfin
      persistentVolumeClaim:
        claimName: jellyfin
    - name: media
      hostPath:
        path: /srv/downloads
    - name: tailscale
      persistentVolumeClaim:
        claimName: jellyfin-tailscale
    - name: funnel
      configMap:
        name: jellyfin-funnel
        items:
          - key: funnel.json
            path: funnel.json
    - name: decoder
      hostPath:
        path: /dev/video10
        type: CharDevice
    - name: encoder
      hostPath:
        path: /dev/video11
        type: CharDevice
    - name: scaler
      hostPath:
        path: /dev/video12
        type: CharDevice
    - name: drm
      hostPath:
        path: /dev/dri
        type: Directory
    - name: jellyfin-cache
      emptyDir: {}
    - name: jellyfin-transcodes
      persistentVolumeClaim:
        claimName: jellyfin-transcodes
  securityContext:
    supplementalGroups:
      - 44
      - 992
  containers:
    - name: jellyfin
      image: docker.io/jellyfin/jellyfin:latest
      volumeMounts:
        - name: jellyfin
          mountPath: /config
        - name: jellyfin-cache
          mountPath: /cache
        - name: jellyfin-transcodes
          mountPath: /cache/transcodes
        - name: media
          mountPath: /media
          readOnly: true
        - name: encoder
          mountPath: /dev/video10
        - name: decoder
          mountPath: /dev/video11
        - name: scaler
          mountPath: /dev/video12
        - name: drm
          mountPath: /dev/dri
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
    - name: tailscale
      image: docker.io/tailscale/tailscale:latest
      volumeMounts:
        - name: tailscale
          mountPath: /var/lib/tailscale
        - name: funnel
          mountPath: /funnel
      env:
        - name: TS_AUTH_ONCE
          value: "0"
        - name: TS_HOSTNAME
          value: jellyfin
        - name: TS_SERVE_CONFIG
          value: /funnel/funnel.json
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
