apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarr
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sarr-config
        - name: data
          persistentVolumeClaim:
            claimName: sarr-data
        - name: downloads
          hostPath:
            path: /srv/downloads
            type: Directory
      containers:
        - image: lscr.io/linuxserver/sonarr:version-4.0.10.2544
          name: sarr
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: UMASK
              value: "000"
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: downloads
              mountPath: /srv/downloads
