---
apiVersion: v1
kind: Pod
metadata:
  name: transmission
spec:
  dnsConfig:
    nameservers:
      - 100.100.100.100
  volumes:
    - name: tailscale
      persistentVolumeClaim:
        claimName: transmission-tailscale
    - name: serve
      configMap:
        name: transmission-serve
        items:
          - key: serve.json
            path: serve.json
    - name: tun
      hostPath:
        path: /dev/net/tun
        type: CharDevice
    - name: transmission
      configMap:
        name: transmission-config
        items:
          - key: settings.json
            path: settings.json
    - name: resume
      persistentVolumeClaim:
        claimName: transmission-resume
    - name: downloads
      hostPath:
        path: /mnt/downloads
  containers:
    - name: app
      image: lscr.io/linuxserver/transmission:latest
      volumeMounts:
        - name: transmission
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: resume
          mountPath: /config/resume
        - name: resume
          mountPath: /config/torrents
    - name: ts
      image: docker.io/tailscale/tailscale:latest
      securityContext:
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
      volumeMounts:
        - name: tun
          mountPath: /dev/net/tun
        - name: tailscale
          mountPath: /var/lib/tailscale
        - name: serve
          mountPath: /config
      env:
        - name: TS_ACCEPT_DNS
          value: "1"
        - name: TS_AUTH_ONCE
          value: "0"
        - name: TS_HOSTNAME
          value: transmission
        - name: TS_SERVE_CONFIG
          value: /config/serve.json
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
        - name: TS_USERSPACE
          value: "0"
        - name: TS_EXTRA_ARGS
          value: --exit-node=100.67.33.82
        - name: TS_TAILSCALED_EXTRA_ARGS
          value: --no-logs-no-support
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale
              key: TS_AUTHKEY
              optional: true
