apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-serve
data:
  serve.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        },
        "80": {
          "HTTP": true
        }
      },
      "Web": {
        "${TS_CERT_DOMAIN}:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://127.0.0.1:9091"
            }
          }
        },
        "${TS_CERT_DOMAIN}:80": {
          "Handlers": {
            "/": {
              "Proxy": "http://127.0.0.1:8080"
            }
          }
        }
      }
    }
