---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett
spec:
  accessModes: [ReadWriteOncePod]
  storageClassName: local-path
  resources:
    requests:
      storage: 16Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jett
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: jackett
          persistentVolumeClaim:
            claimName: jackett
        - name: jackett-run
          emptyDir: {}
      containers:
        - image: lscr.io/linuxserver/jackett:0.22.902
          name: jett
          ports:
            - containerPort: 9117
          volumeMounts:
            - name: jackett
              mountPath: "/config"
            - name: jackett-run
              mountPath: "/run"
          securityContext:
            readOnlyRootFilesystem: true
        - image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
          name: flerr
