---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbt
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          hostPath:
            path: /var/lib/qbittorrent
        - name: downloads
          hostPath:
            path: /srv/downloads
      containers:
        - image: lscr.io/linuxserver/qbittorrent:5.0.0
          name: qbt
          env:
            - name: WEBUI_PORT
              value: "8081"
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: UMASK
              value: "000"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: downloads
              mountPath: "/downloads"
