[
  {
    "name": "Ensure qbittorrent config directory",
    "file":
      { "path": "/var/lib/qbittorrent", "state": "directory", "mode": "0755" },
    "become": true,
  },
  {
    "name": "Run qbittorrent container",
    "community.docker.docker_container":
      {
        "name": "qbittorrent",
        "image": "lscr.io/linuxserver/qbittorrent:latest",
        "restart_policy": "unless-stopped",
        "env":
          {
            "WEBUI_PORT": "{{ qbt_port | string }}",
            "PUID": "{{ nobody | string }}",
            "PGID": "{{ nobody | string }}",
          },
        "published_ports": ["{{ qbt_port }}:{{ qbt_port }}"],
        "volumes": ["/var/lib/qbittorrent:/config"],
        "mounts":
          [
            {
              "source": "/srv/downloads",
              "target": "/downloads",
              "type": "bind",
            },
          ],
        "networks": [{ "name": "torrent" }],
      },
  },
]
