apiVersion: apps/v1
kind: Deployment
metadata:
  name: parr
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: parr
        - name: run
          emptyDir: {}
      containers:
        - image: lscr.io/linuxserver/prowlarr:1.25.4
          name: parr
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: run
              mountPath: "/run"
          securityContext:
            readOnlyRootFilesystem: true
        - image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
          name: flerr
