- name: One time configuration
  hosts: rpi4
  become: true
  collections:
    - containers.podman
  tasks:
    # TODO install tailscale and nix, nopasswd
    - name: Blacklist 8192cu
      copy:
        src: ../blacklist-8192cu.conf
        dest: /etc/modprobe.d/
    - name: journald.conf.d
      file:
        path: /etc/systemd/journald.conf.d
        state: directory
    - name: Memory-only journal
      register: volatile
      copy:
        dest: /etc/systemd/journald.conf.d/volatile.conf
        content: |
          [Journal]
          Storage=volatile
    - name: Restart journald
      when: volatile.changed
      systemd_service:
        name: systemd-journald.service
        state: restarted
    - name: Remove packages
      package:
        state: absent
        name:
          - rsyslogd
          - needrestart
          - snapd
    - name: Delete /var/lib/snapd
      file:
        path: /var/lib/snapd
        state: absent
    - name: Install packages
      package:
        state: present
        name:
          - podman
          - containers-storage
          - systemd-zram-generator
    - name: Load zram module
      community.general.modprobe:
        name: zram
        persistent: present
    - name: Enable zram
      systemd_service:
        name: systemd-zram-setup@zram0.service
        enabled: true
