- name: Tailscale podman secret
  hosts: rpi4
  vars:
    authkey: FAKE
  collections:
    - containers.podman
  tasks:
    - name: Kube
      become: true
      podman_play:
        state: created
        kube_file_content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: tailscale
          data:
            TS_AUTHKEY: {{ authkey | trim | b64encode }}
